# general parameters
ref_type: hg38
project_dir: /cluster/home/sprokope/pipeline_tests/PROJECT
# sample config
fastq_file: /cluster/home/sprokope/pipeline_tests/PROJECT/configs/fastq_file.tsv
# tool details
star_version: STAR/2.7.2b
star_ref: /cluster/projects/pughlab/references/STAR/STAR_2.7.2b_GRCh38_gencode_v31/
picard_version: picard/2.6.0
rsem_version: rsem/1.3.0
rsem_ref: /cluster/projects/pughlab/references/RSEM/GRCh38/v31/grch38.v31
strandedness: reverse
starfusion_version: /cluster/projects/pughlab/bin/STAR-Fusion-1.8.1/STAR-Fusion
starfusion_ref: /cluster/projects/pughlab/references/STAR-Fusion/GRCh38_gencode_v31_CTAT_lib_Oct012019/ctat_genome_lib_build_dir/
samtools_version: samtools/1.9
gatk_version: gatk/3.8
gatk_ref: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
vcf2maf: /cluster/projects/pughlab/bin/vcf2maf-1.6.17/vcf2maf.pl
vep_path: /cluster/tools/software/centos7/vep/98
vep_data: /cluster/projects/pughlab/references/VEP_cache/98
vep_filter: /cluster/projects/pughlab/references/VEP_cache/ExAC_nonTCGA.r1.sites.hg19ToHg38.vep.vcf.gz
