---
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME/RNASeq/fastqc/
HPC_driver: slurm
dry_run: N 
# and indicate some parameters for job submission
parameters:
    fastqc:
        mem: 2G
        time: '24:00:00'
    md5sum:
        mem: 2G
        time: '24:00:00'
