---
PATIENT_ID:
    SAMPLE_ID:
        type: tumour
        libraries:
            LIBRARY_NAME:
                runlanes:
                    LANE_NAME:
#                   ie, 181119_D00355_0257_ACD07PANXX_CAGATCTG-TCTTTCCC_L005
                        fastq:
                            R1: /cluster/projects/pughlab/data/PROJECTNAME/EXOME/SAMPLE_ID_LANE_NAME.R1.fastq.gz
                            R2: /cluster/projects/pughlab/data/PROJECTNAME/EXOME/SAMPLE_ID_LANE_NAME.R2.fastq.gz
    SAMPLE_ID:
        type: normal
        libraries:
            LIBRARY_NAME:
                runlanes:
                    LANE_NAME:
                        fastq:
                            R1: /cluster/projects/pughlab/data/PROJECTNAME/EXOME/SAMPLE_ID_LANE_NAME.R1.fastq.gz
                            R2: /cluster/projects/pughlab/data/PROJECTNAME/EXOME/SAMPLE_ID_LANE_NAME.R2.fastq.gz
