---
tool: rsem
tool_version: 1.3.0
ref_type: hg38
reference: /cluster/projects/pughlab/references/RSEM/GRCh38/v31/grch38.v31
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME/RNASeq/RSEM/ 
#resume_dir: /cluster/projects/pughlab/projects/PROJECTNAME/RNASeq/RSEM/DATE_rsem_version/
resume_dir:
HPC_driver: Slurm
# For Illumina TruSeq Stranded protocols, please use 'reverse'
strandedness: reverse
del_intermediate: N
create_output_yaml: Y
dry_run: N
# and indicate some parameters for job submission
parameters:
    rsem:
        mem: 4G
        time: '24:00:00'
