---
project_name: PROJECTNAME
output_dir: /cluster/projects/pughlab/projects/PROJECTNAME/Exome/
seq_type: exome # must be one of exome, targeted, rna or wgs
seq_center: PMGC
platform: Illumina
# reference files
ref_type: hg38 # must be hg38 or hg19, not compatible with GRCh37/GRCh38 reference (missing _chr_)
reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
intervals_bed:
dbsnp: /cluster/projects/pughlab/references/dbSNP/GRCh38/b151/dbSNP_GRCh38p7_b151_common_chr.vcf.gz
cosmic: /cluster/projects/pughlab/references/COSMIC/GRCh38/v91/CosmicVariants_full_sorted_chr.vcf.gz
hapmap: /cluster/projects/pughlab/references/hapmap/hg38_population_stratified_af_hapmap_3.3.vcf.gz
gtf: /cluster/projects/pughlab/references/gencode/GRCh38/gencode.v31.annotation.gtf
# tool versions
bwa_version: 0.7.15
samtools_version: 1.9
picard_version: 2.6.0
bedtools_version: 2.27.1
gatk_version: 3.8
vcftools_version: 0.1.15
mutect_version: 1.1.5
strelka_version: 2.9.10
manta_version: 1.6.0
varscan_version: 2.4.2
delly_version: 0.8.1
somaticsniper_version: bam-somaticsniper/1.0.5.0 # or SomaticSniper/1.0.4 currently available on h4h
vardict_version: 1.7.0
mavis_version: 2.2.5
cpsr_version: 0.6.1
pcgr_version: 0.9.1
r_version: 3.6.1
# tool specific parameters
bwa:
    run: Y
    aligner: bwamem
    reference: /cluster/projects/pughlab/references/bwa_index/hg38/genome.fa
    parameters:
        bwa:
            mem:
                normal: 8G
                tumour: 8G
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        sort:
            mem:
                normal: 4G
                tumour: 4G
            time:
                normal: '24:00:00'
                tumour: '48:00:00'
        index:
            mem:
                normal: 2G
                tumour: 2G
            time:
                normal: '05:00:00'
                tumour: '05:00:00'
        merge:
            mark_dup: Y
            java_mem:
                normal: 7g
                tumour: 11g
            mem:
                normal: 8G
                tumour: 12G
            time:
                normal: '48:00:00'
                tumour: '48:00:00'
gatk:
    run: Y
    parameters:
        target_creator:
            java_mem: 5g
            mem: 6G
            time: '48:00:00'
        realign:
            java_mem: 3g
            mem: 4G
            time: '72:00:00'
        bqsr:
            java_mem: 11g
            mem: 12G
            time:
                normal: '48:00:00'
                tumour: '72:00:00'
        recalibrate:
            java_mem: 11g
            mem: 12G
            time:
                normal: '48:00:00'
                tumour: '72:00:00'
bamqc:
    run: Y
    parameters:
        contest:
            threshold: '3.0'
            java_mem: 1g
            mem: 2G
            time: '24:00:00'
        coverage:
            java_mem: 3g
            mem: 4G
            time: '48:00:00'
        callable_bases:
            min_depth:
                tumour: 20
                normal: 15
            mem: 4G
            time: '48:00:00'
haplotype_caller:
    run: Y
    parameters:
        haplotype_call:
            java_mem: 3g
            mem: 4G
            time: '72:00:00'
        combine_gvcfs:
            java_mem: 5g
            mem: 6G
            time: '5-00:00:00'
        genotype_gvcfs:
            java_mem: 5g
            mem: 6G
            time: '5-00:00:00'
        vqsr:
            java_mem: 7g
            mem: 8G
            time: '24:00:00'
        apply_vqsr:
            java_mem: 1g
            mem: 2G
            time: '24:00:00'
        filter_recalibrated:
            mem: 2G
            time: '24:00:00'
        cpsr:
            known_positions: PCA_pathVar_integrated_filtered_adjusted_WITH_FANCI_liftover_hg38.tsv
            mem: 4G
            time: '24:00:00'
annotate:
    vcf2maf_path: /cluster/projects/pughlab/bin/vcf2maf-1.6.17/vcf2maf.pl
    vep_path: /cluster/tools/software/centos7/vep/98
    vep_data: /cluster/projects/pughlab/references/VEP_cache/98
    filter_vcf: /cluster/projects/pughlab/references/VEP_cache/ExAC_nonTCGA.r1.sites.hg19ToHg38.vep.vcf.gz 
    mem: 16G
    time: '12:00:00'
mutect:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg38/MuTect/v1.1.5/mutect_v1.1.5_hg38_panel_of_normals_20201128.vcf
    parameters:
        mutect:
            java_mem: 11g
            mem: 12G
            time: '4-00:00:00'
        filter:
            mem: 4G
            time: '12:00:00'
        create_pon:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
mutect2:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg38/Mutect2/v3.8/mutect2_v3.8_hg38_panel_of_normals_20201128.vcf
#    chromosomes: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
    parameters:
        mutect:
            java_mem: 3g
            mem: 4G
            time: '21-00:00:00' # some WXS can take >14 days to complete
        merge:
            mem: 2G
            time: '12:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
strelka:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg38/Strelka/v2.9.10/strelka_v2.9.10_hg38_panel_of_normals_20201128.vcf
    parameters:
        strelka:
            mem: 8G
            time: '24:00:00'
        manta:
            mem: 8G
            time: '24:00:00'
        filter:
            mem: 2G
            time: '12:00:00'
        create_pon:
            java_mem: 3g
            mem: 4G
            time: '96:00:00'
varscan:
    run: Y
    pon: /cluster/projects/pughlab/references/panel_of_normals/hg38/VarScan/v2.4.2/varscan_v2.4.2_hg38_panel_of_normals_20201128.vcf
    parameters:
        varscan:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
        sequenza:
            r: 3.3.0
            path:
            cancer_type_prior: all
            mem: 6G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
somaticsniper:
    run: Y
    pon:
    parameters:
        somaticsniper:
            mem: 4G
            time: '24:00:00'
        pileup:
            mem: 4G
            time: '24:00:00'
        readcount:
            mem: 1G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '24:00:00'
vardict:
    run: Y
    intervals:
    pon: 
    parameters:
        vardict:
            mem: 12G
            time: '12:00:00'
        test_somatic:
            mem: 16G
            time: '24:00:00'
        filter:
            mem: 1G
            time: '12:00:00'
        create_pon:
            java_mem: 3g
            mem: 4G
            time: '24:00:00'
delly:
    run: Y
    parameters:
        call:
            mem: 8G
            time: '72:00:00'
        genotype:
            mem: 6G
            time: '48:00:00'
        merge:
            mem: 2G
            time: '24:00:00'
        filter:
            mem: 2G
            time: '12:00:00'
mavis:
    run: Y
    mavis_annotations: /cluster/projects/pughlab/references/MAVIS_ref/ensembl79_hg38_annotations.json
    mavis_masking: /cluster/projects/pughlab/references/MAVIS_ref/GRCh38_masking.tab
    mavis_dgv_anno: /cluster/projects/pughlab/references/MAVIS_ref/dgv_hg38_variants.tab
    mavis_cytoband: /cluster/projects/pughlab/references/MAVIS_ref/cytoBand.txt
    mavis_draw_fusions_only: false
    mavis_aligner: 'bwa mem'
