---
project_name: PROJECTNAME
output_dir: /path/to/project/directory 
hpc_group: 
# reference files
ref_type: hg38 # currently only tested on hg38 
reference: /cluster/projects/pughlab/references/TGL/hg38/hg38_random.fa
nucleosome_peaks: 
delfi_pon: 
delfi_filters: 
delfi_gaps: 
delfi_vntrs: 
delfi_tiles:  
TFBS_sites: 
TCGA_sites: 
DHS_sites: 
housekeeping_sites: 
# package directories
fragmentomics_dir: 
griffin_dir: 
# tool versions
samtools_version: 1.10
picard_version: 2.10.9
bedtools_version: 2.27.1
python3_version: 3.10.9
r_version: 4.0.0
# tool specific parameters
parameters:
    downsample:
        n_reads: 50000000 # takes priority over scale factor
        scale_factor: 0.01 # scale factor = probability of selecting a read
        mem: 2G
        time: '48:00:00'
    dedup:
        java_mem: 1g
        mem: 2G
        time: '48:00:00'
    ratio:
        mem: 12G
        time: '24:00:00'
    score:
        mem: 2G
        time: '24:00:00'
    insertsize:
        java_mem: 7g
        mem: 8G
        time: '24:00:00'
    nucleosome_position:
        mem: 16G
        time: '12:00:00'
    end_motifs:
        mem: 16G
        time: '12:00:00'
    breakpoints:
        mem: 64G
        time: '12:00:00'
    dinucleotide:
        size: both
        mem: 16G
        time: '12:00:00'
    griffin_gc:
        n_cpus: 8
        time: '12:00:00'
        mem: 16G
    griffin_tfbs:
        n_cpus: 8
        time: '12:00:00'
        mem: 16G
    griffin_tcga:
        n_cpus: 2
        time: '12:00:00'
        mem: 16G
    griffin_dhs:
        n_cpus: 2
        time: '12:00:00'
        mem: 16G
    griffin_housekeeping:
        n_cpus: 2
        time: '12:00:00'
        mem: 16G
