---
tool: fusioncatcher
tool_version: 1.20
ref_type: hg38
reference_dir: /cluster/tools/software/centos7/fusioncatcher/1.20/fusioncatcher/data/current/ 
samtools_version: 1.9
r_version: 3.6.1
# and indicate some parameters for job submission
parameters:
    fusioncatcher:
        java_mem: 35g
        mem: 36G
        time: '72:00:00'
    combine_results:
        mem: 4G
        time: '04:00:00'
