---
tool: gatk
tool_version: 3.8
ref_type: hg38
reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
samtools_version: 1.9
picard_version: 2.6.0
intervals_bed:
dbsnp:
create_output_yaml: Y
# and indicate some parameters for job submission
parameters:
    split_cigar:
        java_mem: 8g
        mem: 12G
        time: '24:00:00'
    target_creator:
        java_mem: 6g
        mem: 8G
        time: '24:00:00'
    realign:
        java_mem: 10g
        mem: 12G
        time: '24:00:00'
    bqsr:
        java_mem: 10g
        mem: 12G
        time:
            normal: '24:00:00'
            tumour: '48:00:00'
    recalibrate:
        java_mem: 10g
        mem: 12G
        time:
            normal: '24:00:00'
            tumour: '48:00:00'
