---
tool: rsem
tool_version: 1.3.0
ref_type: hg38
reference: /cluster/projects/pughlab/references/RSEM/GRCh38/v31/grch38.v31
# For Illumina TruSeq Stranded protocols, please use 'reverse'
strandedness: reverse
r_version: 3.6.1
# and indicate some parameters for job submission
parameters:
    rsem:
        mem: 4G
        time: '12:00:00'
    combine_results:
        run: Y
        mem: 4G
        time: '04:00:00'
