---
tool: STAR
tool_version: 2.7.2b
ref_type: hg38
reference_dir: /cluster/projects/pughlab/references/STAR/STAR_2.7.2b_GRCh38_gencode_v31/
seq_center: PMGC
platform: Illumina
samtools_version: 1.9
picard_version: 2.6.0
rna_seqc_version: 1.1.8
r_version: 3.6.1
mark_dup: Y
# and indicate some parameters for job submission
parameters:
    star:
        mem: 22G
        time: '48:00:00'
    markdup:
        java_mem: 6g
        mem: 8G
        time: '08:00:00'
    rna_seqc:
        java_mem: 4g
        mem: 6G
        time: '48:00:00'
        bwa_path: /cluster/tools/software/bwa/0.7.15/
        reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
        reference_gtf: /cluster/projects/pughlab/references/gencode/GRCh38/gencode.v31.GRCh38.genes.gtf
    combine_results:
        mem: 4G
        time: '04:00:00'
