---
tool: strelka
tool_version: 2.9.10
seq_type: exome # must be one of exome, targeted, rna or wgs
ref_type: hg38
reference: /cluster/tools/data/genomes/human/hg38/iGenomes/Sequence/WholeGenomeFasta/genome.fa
gatk_version: 3.8
samtools_version: 1.9
vcftools_version: 0.1.15
manta_version: 1.6.0
r_version: 3.6.1
intervals_bed: /cluster/projects/ovgroup/projects/OV_Superset/Combined/SureSelect_Human_All_Exon_V5+UTRs__hg38_trimmed_sorted.bed.gz
gtf: /cluster/projects/pughlab/references/gencode/GRCh38/gencode.v31.GRCh38.genes.gtf
# and indicate some parameters for job submission
parameters:
    strelka:
        mem: 6G
        time: '24:00:00'
    manta:
        mem: 6G
        time: '24:00:00'
    filter:
        mem: 2G
        time: '12:00:00'
    annotate:
        vcf2maf_path: /cluster/projects/pughlab/bin/vcf2maf-1.6.17/vcf2maf.pl
        vep_path: /cluster/tools/software/centos7/vep/98
        vep_data: /cluster/projects/pughlab/references/VEP_cache/98
#       filter_vcf: 0
        filter_vcf: /cluster/projects/pughlab/references/VEP_cache/ExAC_nonTCGA.r1.sites.hg19ToHg38.vep.vcf.gz 
        mem:
            snps: 28G
            indels: 8G
        time: '72:00:00'
    combine: # for panel of normals
        java_mem: 3g
        mem: 4G
        time: '48:00:00'
